version: "3"
services:
  doctolib-appointment-finder:
    image: rohitmisra44/doctolib-appointment-finder
    volumes:
      - ./app-config:/app-config
    environment:
      - CONFIG_LOCATION=file:/config/config.properties
    command:
      ["java", "-server", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseContainerSupport", "-XX:InitialRAMFraction=2", "-XX:MinRAMFraction=2", "-XX:MaxRAMFraction=2", "-XX:+UseG1GC", "-XX:MaxGCPauseMillis=100", "-XX:+UseStringDeduplication", "-jar", "app.jar", "--spring.config.location=app-config/application.yaml"]